### ISSUE TITLE
failing tests with LANG=C

### ISSUE THREAD

**Issue by terceiro** [ruby-i18n/i18n#115]
```
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................EEEEEEEEEEE...........................................................................................................................................................................................................................................................................................................................................................................................................

Finished tests in 0.671870s, 1536.0113 tests/s, 2149.2251 assertions/s.

  1) Error:
test_backend_loads_po_file(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:29:in `test_backend_loads_po_file'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  2) Error:
test_looks_up_a_namespaced_translation(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:17:in `sgettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:44:in `test_looks_up_a_namespaced_translation'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  3) Error:
test_looks_up_a_translation(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:11:in `gettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:35:in `test_looks_up_a_translation'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  4) Error:
test_ngettextpluralizes_entry_with_dots(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:43:in `nsgettext'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:28:in `ngettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:89:in `test_ngettextpluralizes_entry_with_dots'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  5) Error:
test_pluralizes_default_entry(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:43:in `nsgettext'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:28:in `ngettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:60:in `test_pluralizes_default_entry'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  6) Error:
test_pluralizes_entry(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:43:in `nsgettext'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:28:in `ngettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:55:in `test_pluralizes_entry'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  7) Error:
test_pluralizes_namespaced_default_entry(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:43:in `nsgettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:73:in `test_pluralizes_namespaced_default_entry'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  8) Error:
test_pluralizes_namespaced_entry(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:43:in `nsgettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:66:in `test_pluralizes_namespaced_entry'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

  9) Error:
test_pluralizes_namespaced_entry_with_alternative_syntax(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:43:in `nsgettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:81:in `test_pluralizes_namespaced_entry_with_alternative_syntax'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

 10) Error:
test_uses_default_translation(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:11:in `gettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:39:in `test_uses_default_translation'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

 11) Error:
test_uses_namespaced_default_translation(I18nGettextBackendTest):
ArgumentError: invalid byte sequence in US-ASCII
    src/poparser.ry:127:in `==='
    src/poparser.ry:127:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:37:in `parse'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/gettext.rb:32:in `load_po'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:157:in `load_file'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `block in load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `each'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:15:in `load_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:57:in `init_translations'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/simple.rb:71:in `lookup'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/backend/base.rb:26:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:156:in `block in translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `catch'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n.rb:152:in `translate'
    /tmp/buildd/ruby-i18n-0.6.0/debian/ruby-i18n/usr/lib/ruby/vendor_ruby/i18n/gettext/helpers.rb:17:in `sgettext'
    /tmp/buildd/ruby-i18n-0.6.0/test/gettext/backend_test.rb:49:in `test_uses_namespaced_default_translation'
    /usr/lib/ruby/vendor_ruby/mocha/integration/mini_test/version_201_to_202.rb:27:in `run'

1032 tests, 1444 assertions, 0 failures, 11 errors, 0 skips
```

To reproduce, just run `LANG=C rake`.

**Comment by voxik** [comment]
Still issue with 0.7.0.

**Comment by radar** [comment]
I am unable to reproduce this issue. @voxik, is this the right command?

```
LANG=C bundle exec rake test
```

**Comment by sandstrom** [comment]
friendly ping @voxik

**Comment by voxik** [comment]
Sorry, I was missing GH notifications for some while :/ This is the command which I am using:

```
$ LANG=C ruby -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'
```

**Comment by voxik** [comment]
And this is my environment:

```
$ gem list

*** LOCAL GEMS ***

json (1.8.3)
metaclass (0.0.4)
minitest (5.8.5)
mocha (1.1.0)
psych (2.1.0)
rdoc (4.2.2)
test_declarative (0.0.5)

$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```

**Comment by radar** [comment]
I've been going back through old issues and I came across this one today. Sorry for not replying sooner @voxik.

I can definitely reproduce this issue with this command:

```
LANG=C bundle exec ruby -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'
```

I believe the issue is in `lib/i18n/gettext/po_parser.rb`, which seems to be a modified version of https://github.com/mutoh/gettext/blob/master/lib/gettext/tools/poparser.rb. I do not feel comfortable changing i18n's version because of how modified it is.

Patches welcome.

**Comment by voxik** [comment]
It is still issue testing with 1.1.1. The patch is actually referenced above (https://github.com/voxik/i18n/commit/8511065417213df97b64d87de5c7c36657cb7115), but not sure if it still applies.

**Comment by voxik** [comment]
Still true for 1.8.2

**Comment by voxik** [comment]
This is sill an issue with 1.14.6 (although the default on Fedora changed to `C.UTF-8`, so it is less problematic)
