### ISSUE TITLE
[BUG] Rails bump causing InvalidLocale error

### ISSUE THREAD

**Issue by etherz10** [ruby-i18n/i18n#541]
## What I tried to do

I tried to update my Rails version from 5.2.4.4 to 6.0.3.3.

## What I expected to happen

For the Rails server to start without any errors.

## What actually happened

When I try to run the rails server it blows up with the following error.

```
$ bundle exec rails server
=> Booting Puma
=> Rails 6.0.3.3 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	54: from bin/rails:4:in `<main>'
	53: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
	52: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
	51: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
	50: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	49: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	48: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	47: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	46: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	45: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<top (required)>'
	44: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/command.rb:46:in `invoke'
	43: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/command/base.rb:69:in `perform'
	42: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	41: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	40: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	39: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:138:in `perform'
	38: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:138:in `tap'
	37: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	36: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:37:in `start'
	35: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	34: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	33: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	32: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	31: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	30: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	29: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	28: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	27: from config.ru:3:in `block in <main>'
	26: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
	25: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
	24: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
	23: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	22: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	21: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	20: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	19: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	18: from /Users/kieron/Documents/GitHub/agora/athena/config/environment.rb:5:in `<top (required)>'
	17: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/application.rb:363:in `initialize!'
	16: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:60:in `run_initializers'
	15: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	14: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	13: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	12: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:347:in `call'
	11: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:347:in `each'
	10: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 9: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 8: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 7: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 6: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	 5: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `run'
	 4: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `instance_exec'
	 3: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-6.0.3.3/lib/rails/application/finisher.rb:36:in `block in <module:Finisher>'
	 2: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.3/lib/active_support/core_ext/array/conversions.rb:70:in `to_sentence'
	 1: from /Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/i18n-1.8.5/lib/i18n.rb:198:in `translate'
/Users/kieron/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/i18n-1.8.5/lib/i18n.rb:342:in `enforce_available_locales!': :"en-GB" is not a valid locale (I18n::InvalidLocale)
```

Even though my `config/application.rb` contains the following

```
  config.i18n.available_locales = [
        :"en-GB",
        :"en-GB@corporate",
        :"en-GB@rcrd",
        :"es-ES",
        :"de-DE",
        :"fr-FR",
        :"nl-NL",
        :"fi-FI",
        :"he-IL",
        :"ar-IL",
        :"zh-CN",
      ]

  config.i18n.enforce_available_locales = false

    # Set language fallback order.
    #
  config.i18n.fallbacks = { :"en-GB" => :en,
                            :"en-GB@corporate" => [:"en-GB", :en],
                            :"en-GB@rcrd" => [:"en-GB", :en],
                            :"es-ES" => [:"en-GB", :en],
                            :"de-DE" => [:"en-GB", :en],
                            :"fr-FR" => [:"en-GB", :en],
                            :"nl-NL" => [:"en-GB", :en],
                            :"fi-FI" => [:"en-GB", :en],
                            :"he-IL" => [:"en-GB", :en],
                            :"ar-IL" => [:"en-GB", :en],
                            :"zh-CN" => [:"en-GB", :en]
                          }
```

## Versions of i18n, rails, and anything else you think is necessary

- Rails 6.0.3.3
- i18n 1.8.5

----

Bonus points for providing an application or a small code example which reproduces the issue.

Thanks! :heart:

**Comment by etherz10** [comment]
I'm still seeing this on i18n 1.8.7 trying to update to Rails 6.1.0

@radar Sorry to bother but I see you're active in this project, do you have any idea/suggestions on how to fix this?

**Comment by radar** [comment]
@etherz10 I can take a look this morning.

**Comment by radar** [comment]
@etherz10 I am unable to reproduce this in a new Rails 6.1.1 application. Could you please provide a minimal reproduction test case that I could clone down?

**Comment by RandieM** [comment]
I have the same problem and I think that it is in combination with the gem "lit".
