### ISSUE TITLE
[BUG] i18n 1.9.0 LoadError: cannot load such file -- i18n/core_ext/hash

### ISSUE THREAD

**Issue by olleolleolle** [ruby-i18n/i18n#603]
## What I tried to do

See the CI run.

```
LoadError: cannot load such file -- i18n/core_ext/hash
```

## What I expected to happen

Passing tests.

## What actually happened

An error in requires. https://github.com/ruby-i18n/i18n/search?q=core_ext shows that i18n/core_ext/hash is still being required, but is probably _removed_?

<details>

```
/opt/hostedtoolcache/Ruby/3.0.3/x64/bin/ruby -w -I"lib:lib:test" /home/runner/work/i18n/i18n/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/api/all_features_test.rb" "test/api/cascade_test.rb" "test/api/chain_test.rb" "test/api/fallbacks_test.rb" "test/api/key_value_test.rb" "test/api/memoize_test.rb" "test/api/override_test.rb" "test/api/pluralization_test.rb" "test/api/simple_test.rb" "test/backend/cache_file_test.rb" "test/backend/cache_test.rb" "test/backend/cascade_test.rb" "test/backend/chain_test.rb" "test/backend/exceptions_test.rb" "test/backend/fallbacks_test.rb" "test/backend/interpolation_compiler_test.rb" "test/backend/key_value_test.rb" "test/backend/memoize_test.rb" "test/backend/metadata_test.rb" "test/backend/pluralization_fallback_test.rb" "test/backend/pluralization_scope_test.rb" "test/backend/pluralization_test.rb" "test/backend/simple_test.rb" "test/backend/transliterator_test.rb" "test/gettext/api_test.rb" "test/gettext/backend_test.rb" "test/i18n/exceptions_test.rb" "test/i18n/gettext_plural_keys_test.rb" "test/i18n/interpolate_test.rb" "test/i18n/load_path_test.rb" "test/i18n/middleware_test.rb" "test/i18n_test.rb" "test/locale/fallbacks_test.rb" "test/locale/tag/rfc4646_test.rb" "test/locale/tag/simple_test.rb" "test/utils_test.rb" 
test_declarative is deprecated for Minitest::Unit::TestCase
test_declarative is deprecated for Minitest::Test
/home/runner/work/i18n/i18n/test/backend/cache_test.rb:65: warning: assigned but unused variable - cache_key
Skipping cache tests using ActiveSupport
/home/runner/work/i18n/i18n/lib/i18n/backend/chain.rb:3:in `require': cannot load such file -- i18n/core_ext/hash (LoadError)
	from /home/runner/work/i18n/i18n/lib/i18n/backend/chain.rb:3:in `<top (required)>'
	from /home/runner/work/i18n/i18n/test/backend/chain_test.rb:2:in `require'
	from /home/runner/work/i18n/i18n/test/backend/chain_test.rb:2:in `<top (required)>'
	from /home/runner/work/i18n/i18n/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
	from /home/runner/work/i18n/i18n/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /home/runner/work/i18n/i18n/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /home/runner/work/i18n/i18n/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
not testing with Cache enabled because active_support can not be found
```

</details>

## Versions of i18n, rails, and anything else you think is necessary

Affected: v1.9.0, which was just released.

**Update**: #602 makes CI green again.

Workaround is simple: in the Gemfile, avoid installing latest release.

```ruby
gem "i18n", "< 1.9.0"
```
----

See the CI output.

In addition, radar just did a greatly reduced the outstanding triage work on this repository. Kudos!

**Comment by schinery** [comment]
Looks like there is a PR to revert the breaking change - https://github.com/ruby-i18n/i18n/issues/603

**Comment by olleolleolle** [comment]
Right, #602 is the Pull Request.

**Comment by schinery** [comment]
Meant #602 🤦🏻‍♂️

**Comment by mpantel** [comment]
Actually this https://github.com/ruby-i18n/i18n/pull/573#issuecomment-1023621489 might be the problem cause...

**Comment by radar** [comment]
I am sorry for stuffing this one up. Clearly #602 should've been merged _and_ I should've looked at the right GH actions build, not the one before the latest.

I've yanked 1.9.0, and have now pushed 1.9.1.

**Comment by pboling** [comment]
This issue came back in 1.10.0?
```
LoadError: cannot load such file -- i18n/core_ext/hash
```
